### ISSUE TITLE
virtual environments

### ISSUE THREAD

**Issue by ixil** [wmvanvliet/jupyter-vim#12]
I'm python virtual environments (via pipenv), what is the correct way to use jupyter-vim in conjunction?

I've tried installing ipython, jupyter in the env, and also exporting the venv as a kernel spec, but I cannot get it to work. (I open vim after I have activated the environment `pipenv shell` `gvim files.py`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ixil/.local/share/vim/plugged/jupyter-vim/pythonx/jupyter_vim.py", line 165, in connect_to_kernel
    from jupyter_client import KernelManager, find_connection_file
  File "/home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/jupyter_client/connect.py", line 23, in <module>
    import zmq
  File "/home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/ixil/.local/share/virtualenvs/dissection_code-0a3WJ118/lib/python3.7/site-packages/zmq/backend/cython/constants.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError

```

**Comment by wmvanvliet** [comment]
Can you try the instructions that are in the current `README.md`, i.e. creating a separate virtual environment for jupyter-vim?

**Comment by ixil** [comment]
Following the exact instructions for me did not work:

- Creating a new virtualenv, activating and running `pip install jupyter`, running `jupyter notebook &` and doing `vim test.py` and doing the `let g:vim_virtualenv_path ` related things did not work. I received an error related to zmq. 

However as I do have **system** install of jupyter it is a matter of selecting the kernel.

```
#virtualenv activated
pip install jupyter-client`
jupyter kernelspec install --user --name='project-name'
vim test.py #:JupyterConnect success :)
```
The flags `jupyter kernelspec install --prefix=...` and `--sys-prefix` may be useful for inside a venv.
